variables:
  CI_SSH_KEY: "../gitlab-ci.pem"

junit:
  image: node:8 # docker image with Maven
  before_script:
    - cd admin
    - npm install
    - chmod 400 $CI_SSH_KEY
  script:
    - npm run buildprod
