variables:
  CI_SSH_KEY: "./gitlab-ci.pem"

junit:
  image: maven:3.6.1-jdk-11 # docker image with Maven
  before_script:
    - . setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
  script:
    - mvn install
    - mvn test
    - mvn compile
    - ls /builds
    #- scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/p1709456/mif03-tps/target/TP-Client-AJAX.war gitlabci@192.168.75.98:/opt/tomcat/webapps/client.war
