variables:
  CI_SSH_KEY: "./gitlab-ci.pem"

junit:
  image: maven:3.6.1-jdk-11 # docker image with Maven
  before_script:
    - . setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
  script:
    - scp -r -o StrictHostKeyChecking=no -i $CI_SSH_KEY /api/* gitlabci@192.168.75.118:/var/www/html/game-express
